project:
  type: book

book:
  title: |
    Code and data for "Gene expression divergence following 
    gene and genome duplications in spatially resolved 
    plant transcriptomes"
  author: 
    - name: Fabricio Almeida-Silva
      orcid: 0000-0002-5314-2964
    - name: Yves Van de Peer
      orcid: 0000-0003-4327-3730
  date: "March 2025"
  chapters:
    - index.qmd
    - chapters/01_creating_spe.qmd
    - chapters/02_obtaining_duplicates_and_rates.qmd
    - chapters/03_genelevel_analyses.qmd
    - chapters/04_expression_divergence_correlations.qmd
    - chapters/05_network-based_expression_divergence.qmd
    - chapters/06_divergence_classes.qmd

bibliography: bibliography.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo

editor: 
  mode: source